In [1]:
import pandas as pd

## Series , DataFrames , Csvs

In [3]:
# 2 datatypes
# series-> one dimensional
series=pd.Series(["orange","mango","banana"])

In [4]:
series

0    orange
1     mango
2    banana
dtype: str

In [5]:
colours = pd.Series(["orange","yellow","yellow"])

This is series -> one dimensional

In [6]:
colours

0    orange
1    yellow
2    yellow
dtype: str

In [8]:
# Dataframe -> 2 dimensional 
fruits = pd.DataFrame({"Names":series, "colour" : colours})
fruits

    Names  colour
0  orange  orange
1   mango  yellow
2  banana  yellow

In [9]:
# import data
students = pd.read_csv("students.csv")
students

    StudentID     Name  Age Department  CGPA
0         101    Alice   20        CSE   8.5
1         102      Bob   21         IT   7.8
2         103  Charlie   19        CSE   9.1
3         104    David   22        ECE   6.9
4         105      Eva   20        CSE   8.8
5         106    Frank   21        EEE   7.2
6         107    Grace   20         IT   9.0
7         108    Henry   23        ECE   6.5
8         109      Ivy   19        CSE   9.3
9         110     Jack   22        EEE   7.7
10        111     Kate   20        CSE   8.2
11        112     Liam   21         IT   7.5
12        113      Mia   19        ECE   8.7
13        114     Noah   22        CSE   8.9
14        115   Olivia   20        EEE   7.1

In [10]:
# Exporting data
students.to_csv("e_students.csv", index = False)

In [11]:
e_students=pd.read_csv("e_students.csv")
e_students

    StudentID     Name  Age Department  CGPA
0         101    Alice   20        CSE   8.5
1         102      Bob   21         IT   7.8
2         103  Charlie   19        CSE   9.1
3         104    David   22        ECE   6.9
4         105      Eva   20        CSE   8.8
5         106    Frank   21        EEE   7.2
6         107    Grace   20         IT   9.0
7         108    Henry   23        ECE   6.5
8         109      Ivy   19        CSE   9.3
9         110     Jack   22        EEE   7.7
10        111     Kate   20        CSE   8.2
11        112     Liam   21         IT   7.5
12        113      Mia   19        ECE   8.7
13        114     Noah   22        CSE   8.9
14        115   Olivia   20        EEE   7.1

## Describing Data

In [15]:
# Attribute
students.dtypes

StudentID       int64
Name              str
Age             int64
Department        str
CGPA          float64
dtype: object

In [18]:
# Columns 
students.columns

Index(['StudentID', 'Name', 'Age', 'Department', 'CGPA'], dtype='str')

In [17]:
students_columns=students.columns
students_columns

Index(['StudentID', 'Name', 'Age', 'Department', 'CGPA'], dtype='str')

In [21]:
# index of the data
students.index

RangeIndex(start=0, stop=15, step=1)

In [23]:
# Describes statical data for all numerical columns( count , mean , std , min)
students.describe()

        StudentID        Age       CGPA
count   15.000000  15.000000  15.000000
mean   108.000000  20.600000   8.080000
std      4.472136   1.242118   0.899365
min    101.000000  19.000000   6.500000
25%    104.500000  20.000000   7.350000
50%    108.000000  20.000000   8.200000
75%    111.500000  21.500000   8.850000
max    115.000000  23.000000   9.300000

In [24]:
# Info give details about data (dtypes and null count)
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   15 non-null     int64
 1   Name        15 non-null     str
 2   Age         15 non-null     int64
 3   Department  15 non-null     str
 4   CGPA        15 non-null     float64
dtypes: float64(1), int64(2), str(2)
memory usage: 732.0 bytes

In [36]:
#sum of all columns and individual columns
students.sum()

StudentID                                                  1620
Name          AliceBobCharlieDavidEvaFrankGraceHenryIvyJackK...
Age                                                         309
Department           CSEITCSEECECSEEEEITECECSEEEECSEITECECSEEEE
CGPA                                                      121.2
dtype: object

In [37]:
students["Age"].sum()

np.int64(309)

In [38]:
students["Age"].mean()

np.float64(20.6)

In [39]:
len(students)

15